### ISSUE TITLE
html code not rendered properly

### ISSUE THREAD

**Issue by DfAC** [DfAC/DfAC.github.io#1]
My HTML code

```
<img src="http://29jedk1t4b4k3o7vu2867f4z.wpengine.netdna-cdn.com/wp-content/uploads/2014/08/Screen-Shot-2014-08-20-at-11.08.35-AM.png" alt="Story cycle" style="width: 350px;"/ alight = "left">
```

shows in post instead of the image requested

**Comment by DfAC** [comment]
Added 

```
markdown: kramdown
kramdown:
   input: GFM #Markdown option messed up my code blocks
   hard_wrap: true 
   highlighter: rouge #see https://sacha.me/articles/jekyll-rouge/
   exclude: [src, .editorconfig, .gitignore, CNAME, Gemfile, Gemfile.lock, README.md]
   parse_block_html: true #fix problems with footnotes and rmd headers display 
timezone: UTC
```

to [config](https://github.com/DfAC/DfAC.github.io/blob/master/_config.yml) but no difference seen
